# Generated by Django 6.0.6 on 2026-08-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_price_listing_starting_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='startingBid',
        ),
    ]
