# Generated by Django 6.0.6 on 2026-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
